
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import { sqliteTable, index, uniqueIndex, foreignKey, integer, text, numeric } from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable('users_sessions', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  expiresAt: text('expires_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('users_sessions_order_idx').on(columns._order), index('users_sessions_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const users = sqliteTable('users', {
  id: integer('id').primaryKey(),
  name: text('name'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  email: text('email').notNull(),
  resetPasswordToken: text('reset_password_token'),
  resetPasswordExpiration: text('reset_password_expiration').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  salt: text('salt'),
  hash: text('hash'),
  loginAttempts: numeric('login_attempts', {mode: 'number'}).default(0),
  lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt), index('users_created_at_idx').on(columns.createdAt), uniqueIndex('users_email_idx').on(columns.email),
]
)


export const media = sqliteTable('media', {
  id: integer('id').primaryKey(),
  alt: text('alt'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  url: text('url'),
  thumbnailURL: text('thumbnail_u_r_l'),
  filename: text('filename'),
  mimeType: text('mime_type'),
  filesize: numeric('filesize', {mode: 'number'}),
  width: numeric('width', {mode: 'number'}),
  height: numeric('height', {mode: 'number'}),
  focalX: numeric('focal_x', {mode: 'number'}),
  focalY: numeric('focal_y', {mode: 'number'}),
}, (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt), index('media_created_at_idx').on(columns.createdAt), uniqueIndex('media_filename_idx').on(columns.filename),
]
)


export const doctors = sqliteTable('doctors', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  photo: integer('photo_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  department: text('department'),
  certified: integer('certified', {mode: 'boolean'}).default(false),
  featured: integer('featured', {mode: 'boolean'}).default(false),
  order: numeric('order', {mode: 'number'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('doctors_slug_idx').on(columns.slug), index('doctors_photo_idx').on(columns.photo), index('doctors_updated_at_idx').on(columns.updatedAt), index('doctors_created_at_idx').on(columns.createdAt),
]
)


export const doctors_locales = sqliteTable('doctors_locales', {
  name: text('name').notNull(),
  specialty: text('specialty').notNull(),
  bio: text('bio'),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('doctors_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [doctors.id],
      name: 'doctors_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const departments = sqliteTable('departments', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  icon: text('icon').notNull(),
  centerOfExcellence: integer('center_of_excellence', {mode: 'boolean'}).default(false),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('departments_slug_idx').on(columns.slug), index('departments_updated_at_idx').on(columns.updatedAt), index('departments_created_at_idx').on(columns.createdAt),
]
)


export const departments_locales = sqliteTable('departments_locales', {
  name: text('name').notNull(),
  description: text('description').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('departments_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [departments.id],
      name: 'departments_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const articles = sqliteTable('articles', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  date: text('date').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  author: text('author').notNull(),
  category: text('category', {enum: ['hospital-news', 'health-tips', 'research', 'events']}).notNull(),
  thumbnail: integer('thumbnail_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  featured: integer('featured', {mode: 'boolean'}).default(false),
  body: text('body'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('articles_slug_idx').on(columns.slug), index('articles_thumbnail_idx').on(columns.thumbnail), index('articles_updated_at_idx').on(columns.updatedAt), index('articles_created_at_idx').on(columns.createdAt),
]
)


export const articles_locales = sqliteTable('articles_locales', {
  title: text('title').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('articles_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [articles.id],
      name: 'articles_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const events_gallery = sqliteTable('events_gallery', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
  image: integer('image_id').notNull().references(() => media.id, {
      onDelete: 'set null'
  }),
}, (columns) => [
    index('events_gallery_order_idx').on(columns._order), index('events_gallery_parent_id_idx').on(columns._parentID), index('events_gallery_image_idx').on(columns.image), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [events.id],
      name: 'events_gallery_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const events_gallery_locales = sqliteTable('events_gallery_locales', {
  caption: text('caption'),
  alt: text('alt').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: text('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('events_gallery_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [events_gallery.id],
      name: 'events_gallery_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const events = sqliteTable('events', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  date: text('date').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  category: text('category', {enum: ['procedure', 'event', 'announcement']}).notNull(),
  thumbnail: integer('thumbnail_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  featured: integer('featured', {mode: 'boolean'}).default(false),
  youtubeUrl: text('youtube_url'),
  body: text('body'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('events_slug_idx').on(columns.slug), index('events_thumbnail_idx').on(columns.thumbnail), index('events_updated_at_idx').on(columns.updatedAt), index('events_created_at_idx').on(columns.createdAt),
]
)


export const events_locales = sqliteTable('events_locales', {
  title: text('title').notNull(),
  summary: text('summary').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('events_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [events.id],
      name: 'events_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const awards = sqliteTable('awards', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  year: numeric('year', {mode: 'number'}).notNull(),
  badgeImage: integer('badge_image_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('awards_slug_idx').on(columns.slug), index('awards_badge_image_idx').on(columns.badgeImage), index('awards_updated_at_idx').on(columns.updatedAt), index('awards_created_at_idx').on(columns.createdAt),
]
)


export const awards_locales = sqliteTable('awards_locales', {
  name: text('name').notNull(),
  body: text('body').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('awards_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [awards.id],
      name: 'awards_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const achievements = sqliteTable('achievements', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  year: numeric('year', {mode: 'number'}).notNull(),
  icon: text('icon'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('achievements_slug_idx').on(columns.slug), index('achievements_updated_at_idx').on(columns.updatedAt), index('achievements_created_at_idx').on(columns.createdAt),
]
)


export const achievements_locales = sqliteTable('achievements_locales', {
  title: text('title').notNull(),
  description: text('description').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('achievements_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [achievements.id],
      name: 'achievements_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const testimonials = sqliteTable('testimonials', {
  id: integer('id').primaryKey(),
  slug: text('slug').notNull(),
  avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null'
  }),
  featured: integer('featured', {mode: 'boolean'}).default(false),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    uniqueIndex('testimonials_slug_idx').on(columns.slug), index('testimonials_avatar_idx').on(columns.avatar), index('testimonials_updated_at_idx').on(columns.updatedAt), index('testimonials_created_at_idx').on(columns.createdAt),
]
)


export const testimonials_locales = sqliteTable('testimonials_locales', {
  name: text('name').notNull(),
  quote: text('quote').notNull(),
  caseType: text('case_type'),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('testimonials_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [testimonials.id],
      name: 'testimonials_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const payload_kv = sqliteTable('payload_kv', {
  id: integer('id').primaryKey(),
  key: text('key').notNull(),
  data: text('data', {mode: 'json'}).notNull(),
}, (columns) => [
    uniqueIndex('payload_kv_key_idx').on(columns.key),
]
)


export const payload_locked_documents = sqliteTable('payload_locked_documents', {
  id: integer('id').primaryKey(),
  globalSlug: text('global_slug'),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug), index('payload_locked_documents_updated_at_idx').on(columns.updatedAt), index('payload_locked_documents_created_at_idx').on(columns.createdAt),
]
)


export const payload_locked_documents_rels = sqliteTable('payload_locked_documents_rels', {
  id: integer('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: text('path').notNull(),
  usersID: integer('users_id'),
  mediaID: integer('media_id'),
  doctorsID: integer('doctors_id'),
  departmentsID: integer('departments_id'),
  articlesID: integer('articles_id'),
  eventsID: integer('events_id'),
  awardsID: integer('awards_id'),
  achievementsID: integer('achievements_id'),
  testimonialsID: integer('testimonials_id'),
}, (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order), index('payload_locked_documents_rels_parent_idx').on(columns.parent), index('payload_locked_documents_rels_path_idx').on(columns.path), index('payload_locked_documents_rels_users_id_idx').on(columns.usersID), index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID), index('payload_locked_documents_rels_doctors_id_idx').on(columns.doctorsID), index('payload_locked_documents_rels_departments_id_idx').on(columns.departmentsID), index('payload_locked_documents_rels_articles_id_idx').on(columns.articlesID), index('payload_locked_documents_rels_events_id_idx').on(columns.eventsID), index('payload_locked_documents_rels_awards_id_idx').on(columns.awardsID), index('payload_locked_documents_rels_achievements_id_idx').on(columns.achievementsID), index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['doctorsID']],
      foreignColumns: [doctors.id],
      name: 'payload_locked_documents_rels_doctors_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['departmentsID']],
      foreignColumns: [departments.id],
      name: 'payload_locked_documents_rels_departments_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['articlesID']],
      foreignColumns: [articles.id],
      name: 'payload_locked_documents_rels_articles_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'payload_locked_documents_rels_events_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['awardsID']],
      foreignColumns: [awards.id],
      name: 'payload_locked_documents_rels_awards_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['achievementsID']],
      foreignColumns: [achievements.id],
      name: 'payload_locked_documents_rels_achievements_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk'
    }).onDelete('cascade'),
]
)


export const payload_preferences = sqliteTable('payload_preferences', {
  id: integer('id').primaryKey(),
  key: text('key'),
  value: text('value', {mode: 'json'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_preferences_key_idx').on(columns.key), index('payload_preferences_updated_at_idx').on(columns.updatedAt), index('payload_preferences_created_at_idx').on(columns.createdAt),
]
)


export const payload_preferences_rels = sqliteTable('payload_preferences_rels', {
  id: integer('id').primaryKey(),
  order: integer('order'),
  parent: integer('parent_id').notNull(),
  path: text('path').notNull(),
  usersID: integer('users_id'),
}, (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order), index('payload_preferences_rels_parent_idx').on(columns.parent), index('payload_preferences_rels_path_idx').on(columns.path), index('payload_preferences_rels_users_id_idx').on(columns.usersID), foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk'
    }).onDelete('cascade'), foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk'
    }).onDelete('cascade'),
]
)


export const payload_migrations = sqliteTable('payload_migrations', {
  id: integer('id').primaryKey(),
  name: text('name'),
  batch: numeric('batch', {mode: 'number'}),
  updatedAt: text('updated_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}, (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt), index('payload_migrations_created_at_idx').on(columns.createdAt),
]
)


export const hospital_settings_contact_hours = sqliteTable('hospital_settings_contact_hours', {
  _order: integer('_order').notNull(),
  _parentID: integer('_parent_id').notNull(),
  id: text('id').primaryKey(),
}, (columns) => [
    index('hospital_settings_contact_hours_order_idx').on(columns._order), index('hospital_settings_contact_hours_parent_id_idx').on(columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hospital_settings.id],
      name: 'hospital_settings_contact_hours_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const hospital_settings_contact_hours_locales = sqliteTable('hospital_settings_contact_hours_locales', {
  day: text('day').notNull(),
  time: text('time').notNull(),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: text('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('hospital_settings_contact_hours_locales_locale_parent_id_uni').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hospital_settings_contact_hours.id],
      name: 'hospital_settings_contact_hours_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)


export const hospital_settings = sqliteTable('hospital_settings', {
  id: integer('id').primaryKey(),
  contact_phone: text('contact_phone'),
  contact_emergencyNumber: text('contact_emergency_number'),
  contact_whatsapp: text('contact_whatsapp'),
  contact_email: text('contact_email'),
  contact_social_facebookUrl: text('contact_social_facebook_url'),
  contact_social_xUrl: text('contact_social_x_url'),
  contact_social_youtubeUrl: text('contact_social_youtube_url'),
  updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
}
)


export const hospital_settings_locales = sqliteTable('hospital_settings_locales', {
  hero_years_value: text('hero_years_value').notNull(),
  hero_years_unit: text('hero_years_unit'),
  hero_departments_value: text('hero_departments_value').notNull(),
  hero_departments_unit: text('hero_departments_unit'),
  hero_patients_value: text('hero_patients_value').notNull(),
  hero_patients_unit: text('hero_patients_unit'),
  hero_staff_value: text('hero_staff_value').notNull(),
  hero_staff_unit: text('hero_staff_unit'),
  contact_address: text('contact_address'),
  id: integer('id').primaryKey(),
  _locale: text('_locale', {enum: ['ar', 'en']}).notNull(),
  _parentID: integer('_parent_id').notNull(),
}, (columns) => [
    uniqueIndex('hospital_settings_locales_locale_parent_id_unique').on(columns._locale, columns._parentID), foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hospital_settings.id],
      name: 'hospital_settings_locales_parent_id_fk'
    }).onDelete('cascade'),
]
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
    }),
      }))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
            relationName: 'sessions',
    }),
      }))
export const relations_media = relations(media, () => ({
  
      }))
export const relations_doctors_locales = relations(doctors_locales, ({ one }) => ({
  _parentID: one(doctors, {
    
    fields: [doctors_locales._parentID],
    references: [doctors.id],
    relationName: '_locales',
    }),
      }))
export const relations_doctors = relations(doctors, ({ one, many }) => ({
  photo: one(media, {
    
    fields: [doctors.photo],
    references: [media.id],
    relationName: 'photo',
    }),
    _locales: many(doctors_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_departments_locales = relations(departments_locales, ({ one }) => ({
  _parentID: one(departments, {
    
    fields: [departments_locales._parentID],
    references: [departments.id],
    relationName: '_locales',
    }),
      }))
export const relations_departments = relations(departments, ({ many }) => ({
  _locales: many(departments_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_articles_locales = relations(articles_locales, ({ one }) => ({
  _parentID: one(articles, {
    
    fields: [articles_locales._parentID],
    references: [articles.id],
    relationName: '_locales',
    }),
      }))
export const relations_articles = relations(articles, ({ one, many }) => ({
  thumbnail: one(media, {
    
    fields: [articles.thumbnail],
    references: [media.id],
    relationName: 'thumbnail',
    }),
    _locales: many(articles_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_events_gallery_locales = relations(events_gallery_locales, ({ one }) => ({
  _parentID: one(events_gallery, {
    
    fields: [events_gallery_locales._parentID],
    references: [events_gallery.id],
    relationName: '_locales',
    }),
      }))
export const relations_events_gallery = relations(events_gallery, ({ one, many }) => ({
  _parentID: one(events, {
    
    fields: [events_gallery._parentID],
    references: [events.id],
    relationName: 'gallery',
    }),
    _locales: many(events_gallery_locales, {
            relationName: '_locales',
    }),
    image: one(media, {
    
    fields: [events_gallery.image],
    references: [media.id],
    relationName: 'image',
    }),
      }))
export const relations_events_locales = relations(events_locales, ({ one }) => ({
  _parentID: one(events, {
    
    fields: [events_locales._parentID],
    references: [events.id],
    relationName: '_locales',
    }),
      }))
export const relations_events = relations(events, ({ one, many }) => ({
  thumbnail: one(media, {
    
    fields: [events.thumbnail],
    references: [media.id],
    relationName: 'thumbnail',
    }),
    gallery: many(events_gallery, {
            relationName: 'gallery',
    }),
    _locales: many(events_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_awards_locales = relations(awards_locales, ({ one }) => ({
  _parentID: one(awards, {
    
    fields: [awards_locales._parentID],
    references: [awards.id],
    relationName: '_locales',
    }),
      }))
export const relations_awards = relations(awards, ({ one, many }) => ({
  badgeImage: one(media, {
    
    fields: [awards.badgeImage],
    references: [media.id],
    relationName: 'badgeImage',
    }),
    _locales: many(awards_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_achievements_locales = relations(achievements_locales, ({ one }) => ({
  _parentID: one(achievements, {
    
    fields: [achievements_locales._parentID],
    references: [achievements.id],
    relationName: '_locales',
    }),
      }))
export const relations_achievements = relations(achievements, ({ many }) => ({
  _locales: many(achievements_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_testimonials_locales = relations(testimonials_locales, ({ one }) => ({
  _parentID: one(testimonials, {
    
    fields: [testimonials_locales._parentID],
    references: [testimonials.id],
    relationName: '_locales',
    }),
      }))
export const relations_testimonials = relations(testimonials, ({ one, many }) => ({
  avatar: one(media, {
    
    fields: [testimonials.avatar],
    references: [media.id],
    relationName: 'avatar',
    }),
    _locales: many(testimonials_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_payload_kv = relations(payload_kv, () => ({
  
      }))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
    mediaID: one(media, {
    
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
    }),
    doctorsID: one(doctors, {
    
    fields: [payload_locked_documents_rels.doctorsID],
    references: [doctors.id],
    relationName: 'doctors',
    }),
    departmentsID: one(departments, {
    
    fields: [payload_locked_documents_rels.departmentsID],
    references: [departments.id],
    relationName: 'departments',
    }),
    articlesID: one(articles, {
    
    fields: [payload_locked_documents_rels.articlesID],
    references: [articles.id],
    relationName: 'articles',
    }),
    eventsID: one(events, {
    
    fields: [payload_locked_documents_rels.eventsID],
    references: [events.id],
    relationName: 'events',
    }),
    awardsID: one(awards, {
    
    fields: [payload_locked_documents_rels.awardsID],
    references: [awards.id],
    relationName: 'awards',
    }),
    achievementsID: one(achievements, {
    
    fields: [payload_locked_documents_rels.achievementsID],
    references: [achievements.id],
    relationName: 'achievements',
    }),
    testimonialsID: one(testimonials, {
    
    fields: [payload_locked_documents_rels.testimonialsID],
    references: [testimonials.id],
    relationName: 'testimonials',
    }),
      }))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
    }),
    usersID: one(users, {
    
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
    }),
      }))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
            relationName: '_rels',
    }),
      }))
export const relations_payload_migrations = relations(payload_migrations, () => ({
  
      }))
export const relations_hospital_settings_contact_hours_locales = relations(hospital_settings_contact_hours_locales, ({ one }) => ({
  _parentID: one(hospital_settings_contact_hours, {
    
    fields: [hospital_settings_contact_hours_locales._parentID],
    references: [hospital_settings_contact_hours.id],
    relationName: '_locales',
    }),
      }))
export const relations_hospital_settings_contact_hours = relations(hospital_settings_contact_hours, ({ one, many }) => ({
  _parentID: one(hospital_settings, {
    
    fields: [hospital_settings_contact_hours._parentID],
    references: [hospital_settings.id],
    relationName: 'contact_hours',
    }),
    _locales: many(hospital_settings_contact_hours_locales, {
            relationName: '_locales',
    }),
      }))
export const relations_hospital_settings_locales = relations(hospital_settings_locales, ({ one }) => ({
  _parentID: one(hospital_settings, {
    
    fields: [hospital_settings_locales._parentID],
    references: [hospital_settings.id],
    relationName: '_locales',
    }),
      }))
export const relations_hospital_settings = relations(hospital_settings, ({ many }) => ({
  contact_hours: many(hospital_settings_contact_hours, {
            relationName: 'contact_hours',
    }),
    _locales: many(hospital_settings_locales, {
            relationName: '_locales',
    }),
      }))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  doctors: typeof doctors
  doctors_locales: typeof doctors_locales
  departments: typeof departments
  departments_locales: typeof departments_locales
  articles: typeof articles
  articles_locales: typeof articles_locales
  events_gallery: typeof events_gallery
  events_gallery_locales: typeof events_gallery_locales
  events: typeof events
  events_locales: typeof events_locales
  awards: typeof awards
  awards_locales: typeof awards_locales
  achievements: typeof achievements
  achievements_locales: typeof achievements_locales
  testimonials: typeof testimonials
  testimonials_locales: typeof testimonials_locales
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  hospital_settings_contact_hours: typeof hospital_settings_contact_hours
  hospital_settings_contact_hours_locales: typeof hospital_settings_contact_hours_locales
  hospital_settings: typeof hospital_settings
  hospital_settings_locales: typeof hospital_settings_locales
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_doctors_locales: typeof relations_doctors_locales
  relations_doctors: typeof relations_doctors
  relations_departments_locales: typeof relations_departments_locales
  relations_departments: typeof relations_departments
  relations_articles_locales: typeof relations_articles_locales
  relations_articles: typeof relations_articles
  relations_events_gallery_locales: typeof relations_events_gallery_locales
  relations_events_gallery: typeof relations_events_gallery
  relations_events_locales: typeof relations_events_locales
  relations_events: typeof relations_events
  relations_awards_locales: typeof relations_awards_locales
  relations_awards: typeof relations_awards
  relations_achievements_locales: typeof relations_achievements_locales
  relations_achievements: typeof relations_achievements
  relations_testimonials_locales: typeof relations_testimonials_locales
  relations_testimonials: typeof relations_testimonials
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_hospital_settings_contact_hours_locales: typeof relations_hospital_settings_contact_hours_locales
  relations_hospital_settings_contact_hours: typeof relations_hospital_settings_contact_hours
  relations_hospital_settings_locales: typeof relations_hospital_settings_locales
  relations_hospital_settings: typeof relations_hospital_settings
}
    

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
    