import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-sqlite'
import { sql } from '@payloadcms/db-sqlite'

// users_tenants.commercePermissions: declare the per-assignment commerce permission matrix.
//
// The reader (cms/src/commerce/permissions.ts) and the commerce access functions
// (cms/src/commerce/plugin/access.ts) read `commercePermissions` off each User→Tenant assignment
// row, but the field was never declared as a `rowFields` entry on the multi-tenant plugin — so
// every non-super-admin user had an empty set, `isCommerceAdmin()` returned false, and
// tenant-admins/editors saw no "Add product" CTA. The field is now declared in payload.config.ts
// via `tenantsArrayField.rowFields`.
//
// IMPORTANT: this migration is paired with a `.json` schema snapshot of the SAME basename
// (20260721_140149_commerce_permissions_field.json). Payload's SQLite adapter loads the schema
// model from the latest snapshot — WITHOUT the snapshot, the adapter doesn't know the new table
// exists and Drizzle generates invalid nested SQL that fails at runtime even though the table is
// present. The snapshot was generated by `payload migrate:create`; the `.ts` body below was trimmed
// to ONLY the actual new table (the generated diff also re-emitted every commerce table added since
// the prior snapshot, which already exist in every live DB and would fail to re-create).
//
// The table mirrors `users_roles` (cms/src/migrations/20260715_051848_multi_tenant.ts:4-13):
// `order` + `parent_id` + `value` + `id`. `parent_id` is `text` because `users_tenants.id` is
// `text PRIMARY KEY` (cms/src/migrations/20260715_051848_multi_tenant.ts:104).
//
// The backfill (idempotent, role-based) grants the documented defaults to existing users:
//   - tenant-admin (role 'admin') → ALL_COMMERCE_PERMISSIONS
//   - editor      (role 'editor') → ['catalog.manage']
//   - super-admin                     → nothing stored (reader grants ALL at read time)

type AssignmentRow = { id: string; role: string }

// Hard-coded (not imported) because migrations must not depend on app runtime modules: the
// migration may run against a DB whose schema predates the current permissions.ts. Mirrors
// ALL_COMMERCE_PERMISSIONS in cms/src/commerce/permissions.ts.
const ALL_COMMERCE_PERMISSIONS = [
  'catalog.manage',
  'inventory.manage',
  'orders.read',
  'orders.manage',
  'payments.refund',
  'fulfillment.manage',
  'customers.manage',
  'promotions.manage',
  'reports.read',
  'settings.manage',
] as const

const EDITOR_DEFAULT = ['catalog.manage'] as const

export async function up({ db }: MigrateUpArgs): Promise<void> {
  // 1. Create the join table for the nested select hasMany. (Matches the generator's output
  //    byte-for-byte; trimmed the unrelated tables from the generated diff.)
  await db.run(sql`CREATE TABLE \`users_tenants_commerce_permissions\` (
  	\`order\` integer NOT NULL,
  	\`parent_id\` text NOT NULL,
  	\`value\` text,
  	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  	FOREIGN KEY (\`parent_id\`) REFERENCES \`users_tenants\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );`)
  await db.run(sql`CREATE INDEX \`users_tenants_commerce_permissions_order_idx\` ON \`users_tenants_commerce_permissions\` (\`order\`);`)
  await db.run(sql`CREATE INDEX \`users_tenants_commerce_permissions_parent_idx\` ON \`users_tenants_commerce_permissions\` (\`parent_id\`);`)

  // 2. Idempotent role-based backfill. Join users_tenants to users_roles to decide the default
  // set per assignment row, and only insert when the row has no existing permissions.
  const { rows: assignments } = await db.run(sql`
    SELECT
      ut.\`id\` AS id,
      (SELECT ur.\`value\` FROM \`users_roles\` ur
        WHERE ur.\`parent_id\` = ut.\`_parent_id\` AND ur.\`value\` IN ('admin','editor','super-admin')
        ORDER BY CASE ur.\`value\`
          WHEN 'admin' THEN 0
          WHEN 'editor' THEN 1
          WHEN 'super-admin' THEN 2
          ELSE 3 END
        LIMIT 1) AS role
    FROM \`users_tenants\` ut
  `)

  for (const row of assignments as unknown as AssignmentRow[]) {
    if (!row.id || !row.role) continue
    if (row.role === 'super-admin') continue

    const { rows: existing } = await db.run(sql`
      SELECT 1 AS hit FROM \`users_tenants_commerce_permissions\` WHERE \`parent_id\` = ${row.id} LIMIT 1
    `)
    if ((existing as unknown as { hit?: number }[]).length > 0) continue

    const permissions = row.role === 'admin' ? ALL_COMMERCE_PERMISSIONS : EDITOR_DEFAULT
    let order = 0
    for (const value of permissions) {
      await db.run(sql`
        INSERT INTO \`users_tenants_commerce_permissions\` (\`order\`, \`parent_id\`, \`value\`)
        VALUES (${order}, ${row.id}, ${value})
      `)
      order += 1
    }
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX IF EXISTS \`users_tenants_commerce_permissions_parent_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`users_tenants_commerce_permissions_order_idx\`;`)
  await db.run(sql`DROP TABLE IF EXISTS \`users_tenants_commerce_permissions\`;`)
}
