import type { CollectionConfig } from 'payload'

export const Events: CollectionConfig = {
  slug: 'events',
  labels: {
    singular: { ar: 'فعالية', en: 'Event' },
    plural: { ar: 'الفعاليات', en: 'Events' },
  },
  admin: { useAsTitle: 'title', defaultColumns: ['title', 'date', 'category', 'featured'] },
  access: { read: () => true },
  fields: [
    { name: 'slug', type: 'text', required: true, unique: true,
      label: { ar: 'المعرّف', en: 'Slug' },
      admin: { description: 'Markdown filename. Lowercase, hyphenated.' } },
    { name: 'title', type: 'text', required: true, localized: true,
      label: { ar: 'العنوان', en: 'Title' } },
    { name: 'date', type: 'date', required: true,
      label: { ar: 'التاريخ', en: 'Date' } },
    { name: 'category', type: 'select', required: true,
      label: { ar: 'التصنيف', en: 'Category' },
      options: [
        { label: { ar: 'إجراء', en: 'Procedure' }, value: 'procedure' },
        { label: { ar: 'فعالية', en: 'Event' }, value: 'event' },
        { label: { ar: 'إعلان', en: 'Announcement' }, value: 'announcement' },
      ] },
    { name: 'summary', type: 'textarea', required: true, localized: true,
      label: { ar: 'الملخّص', en: 'Summary' } },
    { name: 'thumbnail', type: 'upload', relationTo: 'media',
      label: { ar: 'الصورة المصغّرة', en: 'Thumbnail' } },
    { name: 'featured', type: 'checkbox', defaultValue: false,
      label: { ar: 'مميّز', en: 'Featured' } },
    { name: 'youtubeUrl', type: 'text',
      label: { ar: 'رابط يوتيوب', en: 'YouTube URL' } },
    { name: 'gallery', type: 'array',
      label: { ar: 'المعرض', en: 'Gallery' },
      fields: [
        { name: 'image', type: 'upload', relationTo: 'media', required: true,
          label: { ar: 'الصورة', en: 'Image' } },
        { name: 'caption', type: 'text', localized: true,
          label: { ar: 'التعليق', en: 'Caption' } },
        { name: 'alt', type: 'text', required: true, localized: true,
          label: { ar: 'النص البديل', en: 'Alt text' } },
      ] },
    { name: 'body', type: 'textarea',
      label: { ar: 'المحتوى', en: 'Body' },
      admin: { description: 'Markdown body' } },
  ],
}
